treename: null
selection: null
test_time_selection: null
preprocess:
  method: auto
  data_fraction: 0.1
  params:
    pfcand_thetarel:
      length: 75
      pad_mode: wrap
      center: 0.34858930110931396
      scale: 1.624477460345415
      min: -5
      max: 5
      pad_value: 0
    pfcand_phirel:
      length: 75
      pad_mode: wrap
      center: 0.0002508459583623335
      scale: 0.46921219429117506
      min: -5
      max: 5
      pad_value: 0
    pfcand_erel_log:
      length: 75
      pad_mode: wrap
      center: -1.7994367480278015
      scale: 1.5875406726241756
      min: -5
      max: 5
      pad_value: 0
    pfcand_dptdpt:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111111001
      min: -5
      max: 5
      pad_value: 0
    pfcand_detadeta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111039416054
      min: -5
      max: 5
      pad_value: 0
    pfcand_dphidphi:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111107874390823
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxydxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11110580506892796
      min: -5
      max: 5
      pad_value: 0
    pfcand_dzdz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111063910034374
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxydz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111103624894281
      min: -5
      max: 5
      pad_value: 0
    pfcand_dphidxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111118613240914
      min: -5
      max: 5
      pad_value: 0
    pfcand_dlambdadz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111195979013
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxyc:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111108128632
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxyctgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111113937755
      min: -5
      max: 5
      pad_value: 0
    pfcand_phic:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111115199
      min: -5
      max: 5
      pad_value: 0
    pfcand_phidz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111110646074
      min: -5
      max: 5
      pad_value: 0
    pfcand_phictgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111049575054
      min: -5
      max: 5
      pad_value: 0
    pfcand_cdz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111018981
      min: -5
      max: 5
      pad_value: 0
    pfcand_cctgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.1111111111111259
      min: -5
      max: 5
      pad_value: 0
    pfcand_mtof:
      length: 75
      pad_mode: wrap
      center: 0.07034343481063843
      scale: 5.023740784756837
      min: -5
      max: 5
      pad_value: 0
    pfcand_dndx:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 0.7164463420754291
      min: -5
      max: 5
      pad_value: 0
    pfcand_charge:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isMu:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isEl:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isChargedHad:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isGamma:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isNeutralHad:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11104002454033693
      min: -5
      max: 5
      pad_value: 0
    pfcand_dz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11108371187249268
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip2dVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11100774440387015
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip2dSig:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.10334593416625304
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip3dVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11100299742888067
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip3dSig:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.10325170267527735
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagJetDistVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.1110667488150603
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagJetDistSig:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.10776096305560455
      min: -5
      max: 5
      pad_value: 0
    pfcand_type:
      length: 75
      pad_mode: wrap
      center: 22.0
      scale: 0.045454545454545456
      min: -5
      max: 5
      pad_value: 0
    pfcand_e:
      length: 75
      pad_mode: wrap
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
    pfcand_p:
      length: 75
      pad_mode: wrap
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
    pfcand_mask:
      length: 75
      pad_mode: constant
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
new_variables:
  pfcand_mask: ak.ones_like(pfcand_e)
inputs:
  pf_points:
    pad_mode: wrap
    length: 75
    vars:
    - pfcand_thetarel
    - pfcand_phirel
  pf_features:
    pad_mode: wrap
    length: 75
    vars:
    - pfcand_erel_log
    - pfcand_thetarel
    - pfcand_phirel
    - pfcand_dptdpt
    - pfcand_detadeta
    - pfcand_dphidphi
    - pfcand_dxydxy
    - pfcand_dzdz
    - pfcand_dxydz
    - pfcand_dphidxy
    - pfcand_dlambdadz
    - pfcand_dxyc
    - pfcand_dxyctgtheta
    - pfcand_phic
    - pfcand_phidz
    - pfcand_phictgtheta
    - pfcand_cdz
    - pfcand_cctgtheta
    - pfcand_mtof
    - pfcand_dndx
    - pfcand_charge
    - pfcand_isMu
    - pfcand_isEl
    - pfcand_isChargedHad
    - pfcand_isGamma
    - pfcand_isNeutralHad
    - pfcand_dxy
    - pfcand_dz
    - pfcand_btagSip2dVal
    - pfcand_btagSip2dSig
    - pfcand_btagSip3dVal
    - pfcand_btagSip3dSig
    - pfcand_btagJetDistVal
    - pfcand_btagJetDistSig
    - pfcand_type
  pf_vectors:
    length: 75
    pad_mode: wrap
    vars:
    - - pfcand_e
      - null
    - - pfcand_p
      - null
    - - pfcand_e
      - null
    - - pfcand_e
      - null
  pf_mask:
    length: 75
    pad_mode: constant
    vars:
    - - pfcand_mask
      - null
labels:
  type: simple
  value:
  - recojet_isG
  - recojet_isU
  - recojet_isS
  - recojet_isC
  - recojet_isB
  - recojet_isTAU
  - recojet_isD
observers: []
monitor_variables: []
weights:
  use_precomputed_weights: false
  reweight_method: flat
  reweight_vars:
    jet_phi:
    - -10.0
    - 10.0
    jet_theta:
    - -10.0
    - 10.0
  reweight_classes:
  - recojet_isG
  - recojet_isU
  - recojet_isS
  - recojet_isC
  - recojet_isB
  - recojet_isTAU
  - recojet_isD
  class_weights:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  reweight_hists:
    recojet_isG:
    - - 0.8999999761581421
    recojet_isU:
    - - 0.8999999761581421
    recojet_isS:
    - - 0.8999999761581421
    recojet_isC:
    - - 0.8999999761581421
    recojet_isB:
    - - 0.8999999761581421
    recojet_isTAU:
    - - 0.8999999761581421
    recojet_isD:
    - - 0.8999999761581421
