treename: null
selection: null
test_time_selection: null
preprocess:
  method: auto
  data_fraction: 0.1
  params:
    pfcand_thetarel:
      length: 75
      pad_mode: wrap
      center: 0.2929884344339371
      scale: 1.3254834259722554
      min: -5
      max: 5
      pad_value: 0
    pfcand_phirel:
      length: 75
      pad_mode: wrap
      center: -0.0050664597656577826
      scale: 0.46680723210904085
      min: -5
      max: 5
      pad_value: 0
    pfcand_erel_log:
      length: 75
      pad_mode: wrap
      center: -1.5753647089004517
      scale: 1.7425410605813612
      min: -5
      max: 5
      pad_value: 0
    pfcand_dptdpt:
      length: 75
      pad_mode: wrap
      center: 1.5855900576886017e-12
      scale: 1159927365.7653437
      min: -5
      max: 5
      pad_value: 0
    pfcand_detadeta:
      length: 75
      pad_mode: wrap
      center: 2.858808784367284e-06
      scale: 13115.782725752068
      min: -5
      max: 5
      pad_value: 0
    pfcand_dphidphi:
      length: 75
      pad_mode: wrap
      center: 1.9056549831475422e-06
      scale: 29349.152865958244
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxydxy:
      length: 75
      pad_mode: wrap
      center: 0.00038672579103149474
      scale: 51.031285463532555
      min: -5
      max: 5
      pad_value: 0
    pfcand_dzdz:
      length: 75
      pad_mode: wrap
      center: 0.0005860007368028164
      scale: 21.48951394696287
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxydz:
      length: 75
      pad_mode: wrap
      center: 2.590501424482028e-10
      scale: 126311.51858958993
      min: -5
      max: 5
      pad_value: 0
    pfcand_dphidxy:
      length: 75
      pad_mode: wrap
      center: -2.7792822947958484e-05
      scale: 1413.272419703965
      min: -5
      max: 5
      pad_value: 0
    pfcand_dlambdadz:
      length: 75
      pad_mode: wrap
      center: -4.280383109289687e-05
      scale: 675.5987105273625
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxyc:
      length: 75
      pad_mode: wrap
      center: -6.705627719760798e-10
      scale: 2150079.1927988976
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxyctgtheta:
      length: 75
      pad_mode: wrap
      center: -5.16281201817792e-12
      scale: 1538497.5361919152
      min: -5
      max: 5
      pad_value: 0
    pfcand_phic:
      length: 75
      pad_mode: wrap
      center: 5.1482094629018427e-11
      scale: 39373443.245511375
      min: -5
      max: 5
      pad_value: 0
    pfcand_phidz:
      length: 75
      pad_mode: wrap
      center: -1.5272509277207413e-12
      scale: 1288010.788513132
      min: -5
      max: 5
      pad_value: 0
    pfcand_phictgtheta:
      length: 75
      pad_mode: wrap
      center: 1.4542684276860202e-13
      scale: 15269326.846813666
      min: -5
      max: 5
      pad_value: 0
    pfcand_cdz:
      length: 75
      pad_mode: wrap
      center: -2.2638601300387692e-14
      scale: 14557406.415222218
      min: -5
      max: 5
      pad_value: 0
    pfcand_cctgtheta:
      length: 75
      pad_mode: wrap
      center: 7.751039416948696e-16
      scale: 250821854.33411863
      min: -5
      max: 5
      pad_value: 0
    pfcand_charge:
      length: 75
      pad_mode: wrap
      center: 1.0
      scale: 0.5
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxy:
      length: 75
      pad_mode: wrap
      center: -0.00010568618381512351
      scale: 18.69798069704089
      min: -5
      max: 5
      pad_value: 0
    pfcand_dz:
      length: 75
      pad_mode: wrap
      center: 7.064762712616357e-07
      scale: 11.790228255098839
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip2dVal:
      length: 75
      pad_mode: wrap
      center: 0.0023444805992767215
      scale: 11.439577746058637
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip2dSig:
      length: 75
      pad_mode: wrap
      center: 0.1697738692164421
      scale: 0.3891679534657247
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip3dVal:
      length: 75
      pad_mode: wrap
      center: 0.0037749713519588113
      scale: 5.895594660008076
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip3dSig:
      length: 75
      pad_mode: wrap
      center: 0.25413817167282104
      scale: 0.5248729676419811
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagJetDistVal:
      length: 75
      pad_mode: wrap
      center: -3.0878511552145937e-06
      scale: 19.676154670540846
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagJetDistSig:
      length: 75
      pad_mode: wrap
      center: -0.00016150626470334828
      scale: 0.9684990699068129
      min: -5
      max: 5
      pad_value: 0
    pfcand_e:
      length: 75
      pad_mode: wrap
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
    pfcand_p:
      length: 75
      pad_mode: wrap
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
    pfcand_mask:
      length: 75
      pad_mode: constant
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
new_variables:
  pfcand_mask: ak.ones_like(pfcand_e)
inputs:
  pf_points:
    pad_mode: wrap
    length: 75
    vars:
    - pfcand_thetarel
    - pfcand_phirel
  pf_features:
    pad_mode: wrap
    length: 75
    vars:
    - pfcand_erel_log
    - pfcand_thetarel
    - pfcand_phirel
    - pfcand_dptdpt
    - pfcand_detadeta
    - pfcand_dphidphi
    - pfcand_dxydxy
    - pfcand_dzdz
    - pfcand_dxydz
    - pfcand_dphidxy
    - pfcand_dlambdadz
    - pfcand_dxyc
    - pfcand_dxyctgtheta
    - pfcand_phic
    - pfcand_phidz
    - pfcand_phictgtheta
    - pfcand_cdz
    - pfcand_cctgtheta
    - pfcand_charge
    - pfcand_dxy
    - pfcand_dz
    - pfcand_btagSip2dVal
    - pfcand_btagSip2dSig
    - pfcand_btagSip3dVal
    - pfcand_btagSip3dSig
    - pfcand_btagJetDistVal
    - pfcand_btagJetDistSig
  pf_vectors:
    length: 75
    pad_mode: wrap
    vars:
    - - pfcand_e
      - null
    - - pfcand_p
      - null
    - - pfcand_e
      - null
    - - pfcand_e
      - null
  pf_mask:
    length: 75
    pad_mode: constant
    vars:
    - - pfcand_mask
      - null
labels:
  type: simple
  value:
  - recojet_isG
  - recojet_isU
  - recojet_isS
  - recojet_isC
  - recojet_isB
  - recojet_isD
  - recojet_isTAU
observers: []
monitor_variables: []
weights:
  use_precomputed_weights: false
  reweight_method: flat
  reweight_vars:
    jet_phi:
    - -10.0
    - 10.0
    jet_theta:
    - -10.0
    - 10.0
  reweight_classes:
  - recojet_isG
  - recojet_isU
  - recojet_isS
  - recojet_isC
  - recojet_isB
  - recojet_isD
  - recojet_isTAU
  class_weights:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  reweight_hists:
    recojet_isG:
    - - 0.8998008370399475
    recojet_isU:
    - - 0.8999999761581421
    recojet_isS:
    - - 0.8815984129905701
    recojet_isC:
    - - 0.8811391592025757
    recojet_isB:
    - - 0.8810675740242004
    recojet_isD:
    - - 0.881497323513031
    recojet_isTAU:
    - - 0.891802966594696
