treename: null
selection: null
test_time_selection: null
preprocess:
  method: auto
  data_fraction: 0.1
  params:
    pfcand_thetarel:
      length: 75
      pad_mode: wrap
      center: 0.19989179074764252
      scale: 3.0065912710784723
      min: -5
      max: 5
      pad_value: 0
    pfcand_phirel:
      length: 75
      pad_mode: wrap
      center: -0.0009248279384337366
      scale: 0.48174487021246765
      min: -5
      max: 5
      pad_value: 0
    pfcand_erel_log:
      length: 75
      pad_mode: wrap
      center: -1.636968970298767
      scale: 1.7028115058518232
      min: -5
      max: 5
      pad_value: 0
    pfcand_dptdpt:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111107541
      min: -5
      max: 5
      pad_value: 0
    pfcand_detadeta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111106911727514
      min: -5
      max: 5
      pad_value: 0
    pfcand_dphidphi:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111108435762071
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxydxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11110641923101715
      min: -5
      max: 5
      pad_value: 0
    pfcand_dzdz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11110385866780098
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxydz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111110856783415
      min: -5
      max: 5
      pad_value: 0
    pfcand_dphidxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111116443934732
      min: -5
      max: 5
      pad_value: 0
    pfcand_dlambdadz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111118398574683
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxyc:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111162746
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxyctgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111102263187
      min: -5
      max: 5
      pad_value: 0
    pfcand_phic:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111027745
      min: -5
      max: 5
      pad_value: 0
    pfcand_phidz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111102052108
      min: -5
      max: 5
      pad_value: 0
    pfcand_phictgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111110677244
      min: -5
      max: 5
      pad_value: 0
    pfcand_cdz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111110894882
      min: -5
      max: 5
      pad_value: 0
    pfcand_cctgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111095155
      min: -5
      max: 5
      pad_value: 0
    pfcand_mtof:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_dndx:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_charge:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isMu:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isEl:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isChargedHad:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isGamma:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isNeutralHad:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.111036469171116
      min: -5
      max: 5
      pad_value: 0
    pfcand_dz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11104270351050112
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip2dVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11100511823494785
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip2dSig:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 0.004981527599528422
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip3dVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11095031129831176
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip3dSig:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 0.0049798788503357195
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagJetDistVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11104738218362929
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagJetDistSig:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 0.004992495727111622
      min: -5
      max: 5
      pad_value: 0
    pfcand_type:
      length: 75
      pad_mode: wrap
      center: 22.0
      scale: 0.004291845493562232
      min: -5
      max: 5
      pad_value: 0
    pfcand_e:
      length: 75
      pad_mode: wrap
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
    pfcand_p:
      length: 75
      pad_mode: wrap
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
    pfcand_mask:
      length: 75
      pad_mode: constant
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
new_variables:
  pfcand_mask: ak.ones_like(pfcand_e)
inputs:
  pf_points:
    pad_mode: wrap
    length: 75
    vars:
    - pfcand_thetarel
    - pfcand_phirel
  pf_features:
    pad_mode: wrap
    length: 75
    vars:
    - pfcand_erel_log
    - pfcand_thetarel
    - pfcand_phirel
    - pfcand_dptdpt
    - pfcand_detadeta
    - pfcand_dphidphi
    - pfcand_dxydxy
    - pfcand_dzdz
    - pfcand_dxydz
    - pfcand_dphidxy
    - pfcand_dlambdadz
    - pfcand_dxyc
    - pfcand_dxyctgtheta
    - pfcand_phic
    - pfcand_phidz
    - pfcand_phictgtheta
    - pfcand_cdz
    - pfcand_cctgtheta
    - pfcand_mtof
    - pfcand_dndx
    - pfcand_charge
    - pfcand_isMu
    - pfcand_isEl
    - pfcand_isChargedHad
    - pfcand_isGamma
    - pfcand_isNeutralHad
    - pfcand_dxy
    - pfcand_dz
    - pfcand_btagSip2dVal
    - pfcand_btagSip2dSig
    - pfcand_btagSip3dVal
    - pfcand_btagSip3dSig
    - pfcand_btagJetDistVal
    - pfcand_btagJetDistSig
    - pfcand_type
  pf_vectors:
    length: 75
    pad_mode: wrap
    vars:
    - - pfcand_e
      - null
    - - pfcand_p
      - null
    - - pfcand_e
      - null
    - - pfcand_e
      - null
  pf_mask:
    length: 75
    pad_mode: constant
    vars:
    - - pfcand_mask
      - null
labels:
  type: simple
  value:
  - recojet_isG
  - recojet_isU
  - recojet_isS
  - recojet_isC
  - recojet_isB
  - recojet_isD
  - recojet_isTAU
observers: []
monitor_variables: []
weights:
  use_precomputed_weights: false
  reweight_method: flat
  reweight_vars:
    jet_phi:
    - -10.0
    - 10.0
    jet_theta:
    - -10.0
    - 10.0
  reweight_classes:
  - recojet_isG
  - recojet_isU
  - recojet_isS
  - recojet_isC
  - recojet_isB
  - recojet_isD
  - recojet_isTAU
  class_weights:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  reweight_hists:
    recojet_isG:
    - - 0.8812500238418579
    recojet_isU:
    - - 0.8999999761581421
    recojet_isS:
    - - 0.8812500238418579
    recojet_isC:
    - - 0.8812500238418579
    recojet_isB:
    - - 0.8812500238418579
    recojet_isD:
    - - 0.8999999761581421
    recojet_isTAU:
    - - 0.8817827701568604
