treename: null
selection: null
test_time_selection: null
preprocess:
  method: auto
  data_fraction: 0.1
  params:
    pfcand_thetarel:
      length: 75
      pad_mode: wrap
      center: 0.19925042241811752
      scale: 3.0062747826945055
      min: -5
      max: 5
      pad_value: 0
    pfcand_phirel:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 0.4815372084914541
      min: -5
      max: 5
      pad_value: 0
    pfcand_erel_log:
      length: 75
      pad_mode: wrap
      center: -1.6372293829917908
      scale: 1.7013414940966938
      min: -5
      max: 5
      pad_value: 0
    pfcand_dptdpt:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111107554
      min: -5
      max: 5
      pad_value: 0
    pfcand_detadeta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111106916662641
      min: -5
      max: 5
      pad_value: 0
    pfcand_dphidphi:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111108440181686
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxydxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11110641947502316
      min: -5
      max: 5
      pad_value: 0
    pfcand_dzdz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11110386869131843
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxydz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111110859551074
      min: -5
      max: 5
      pad_value: 0
    pfcand_dphidxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111116430930763
      min: -5
      max: 5
      pad_value: 0
    pfcand_dlambdadz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111118384953197
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxyc:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.1111111111116263
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxyctgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.1111111110225051
      min: -5
      max: 5
      pad_value: 0
    pfcand_phic:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111028096
      min: -5
      max: 5
      pad_value: 0
    pfcand_phidz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111102003442
      min: -5
      max: 5
      pad_value: 0
    pfcand_phictgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111110681228
      min: -5
      max: 5
      pad_value: 0
    pfcand_cdz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.1111111111089513
      min: -5
      max: 5
      pad_value: 0
    pfcand_cctgtheta:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11111111111095405
      min: -5
      max: 5
      pad_value: 0
    pfcand_mtof:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_dndx:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_charge:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isMu:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isEl:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isChargedHad:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isGamma:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_isNeutralHad:
      length: 75
      pad_mode: wrap
      center: 0.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_dxy:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11103598462332182
      min: -5
      max: 5
      pad_value: 0
    pfcand_dz:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11104277029512223
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip2dVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11100509700456711
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip2dSig:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 0.004981490828075447
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip3dVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11095031258509336
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagSip3dSig:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 0.004979885354132377
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagJetDistVal:
      length: 75
      pad_mode: wrap
      center: -9.0
      scale: 0.11104732869103291
      min: -5
      max: 5
      pad_value: 0
    pfcand_btagJetDistSig:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 0.004992492162958881
      min: -5
      max: 5
      pad_value: 0
    pfcand_type:
      length: 75
      pad_mode: wrap
      center: 22.0
      scale: 0.004291845493562232
      min: -5
      max: 5
      pad_value: 0
    pfcand_V0_x:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_V0_y:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_V0_z:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_V0_M:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_SV_x:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_SV_y:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_SV_z:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_SV_M:
      length: 75
      pad_mode: wrap
      center: -200.0
      scale: 1.0
      min: -5
      max: 5
      pad_value: 0
    pfcand_e:
      length: 75
      pad_mode: wrap
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
    pfcand_p:
      length: 75
      pad_mode: wrap
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
    pfcand_mask:
      length: 75
      pad_mode: constant
      center: null
      scale: 1
      min: -5
      max: 5
      pad_value: 0
new_variables:
  pfcand_mask: ak.ones_like(pfcand_e)
inputs:
  pf_points:
    pad_mode: wrap
    length: 75
    vars:
    - pfcand_thetarel
    - pfcand_phirel
  pf_features:
    pad_mode: wrap
    length: 75
    vars:
    - pfcand_erel_log
    - pfcand_thetarel
    - pfcand_phirel
    - pfcand_dptdpt
    - pfcand_detadeta
    - pfcand_dphidphi
    - pfcand_dxydxy
    - pfcand_dzdz
    - pfcand_dxydz
    - pfcand_dphidxy
    - pfcand_dlambdadz
    - pfcand_dxyc
    - pfcand_dxyctgtheta
    - pfcand_phic
    - pfcand_phidz
    - pfcand_phictgtheta
    - pfcand_cdz
    - pfcand_cctgtheta
    - pfcand_mtof
    - pfcand_dndx
    - pfcand_charge
    - pfcand_isMu
    - pfcand_isEl
    - pfcand_isChargedHad
    - pfcand_isGamma
    - pfcand_isNeutralHad
    - pfcand_dxy
    - pfcand_dz
    - pfcand_btagSip2dVal
    - pfcand_btagSip2dSig
    - pfcand_btagSip3dVal
    - pfcand_btagSip3dSig
    - pfcand_btagJetDistVal
    - pfcand_btagJetDistSig
    - pfcand_type
    - pfcand_V0_x
    - pfcand_V0_y
    - pfcand_V0_z
    - pfcand_V0_M
    - pfcand_SV_x
    - pfcand_SV_y
    - pfcand_SV_z
    - pfcand_SV_M
  pf_vectors:
    length: 75
    pad_mode: wrap
    vars:
    - - pfcand_e
      - null
    - - pfcand_p
      - null
    - - pfcand_e
      - null
    - - pfcand_e
      - null
  pf_mask:
    length: 75
    pad_mode: constant
    vars:
    - - pfcand_mask
      - null
labels:
  type: simple
  value:
  - recojet_isG
  - recojet_isU
  - recojet_isS
  - recojet_isC
  - recojet_isB
  - recojet_isD
  - recojet_isTAU
observers: []
monitor_variables: []
weights:
  use_precomputed_weights: false
  reweight_method: flat
  reweight_vars:
    jet_phi:
    - -10.0
    - 10.0
    jet_theta:
    - -10.0
    - 10.0
  reweight_classes:
  - recojet_isG
  - recojet_isU
  - recojet_isS
  - recojet_isC
  - recojet_isB
  - recojet_isD
  - recojet_isTAU
  class_weights:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  reweight_hists:
    recojet_isG:
    - - 0.899344801902771
    recojet_isU:
    - - 0.899344801902771
    recojet_isS:
    - - 0.8647546172142029
    recojet_isC:
    - - 0.899344801902771
    recojet_isB:
    - - 0.8647546172142029
    recojet_isD:
    - - 0.899344801902771
    recojet_isTAU:
    - - 0.8999999761581421
